mysite/mysite/urls.py
from django.urls import include, path
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ticketbooking.urls')),
]

mysite/ticketbooking/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "ticket"

urlpatterns = [
    path('', views.index, name='index'),
    path('account/login/', auth_views.LoginView.as_view(), name="login"),
    path('account/logout/',auth_views.LogoutView.as_view(), name="logout"),
    path('signup/',views.signup,name="signup"),
    path('book/', views.book, name='book'),
    path('transcaction/', views.tran, name='tran'),
    path('receipt/', views.receipt, name='receipt'),

]

mysite/ticketbooking/models.py
from django.db import models

# Create your models here.

mysite/ticketbooking/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from pymongo import MongoClient, errors, DESCENDING, ASCENDING
from pymongo.auth import authenticate
from django.contrib.auth.decorators import login_required

client = MongoClient("mongodb+srv://Cassie:Cassie@cassie-kdpcc.mongodb.net/test?retryWrites=true&w=majority")
database = client["ticketbooking"]
db = database["booking"]


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            print(username)
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('ticket:index')
    else:
        form = UserCreationForm()
    return render(request, 'ticketbooking/register.html', {'form': form})


@login_required
def index(request):
    return render(request, 'ticketbooking/home.html')


@login_required
def book(request):
    if request.POST:
        if request.POST['source'] == request.POST["dest"]:
            return render(request, 'ticketbooking/book.html', {
                'msg': 'Source and destination cannot be same'
            })
        pass_data = dict()
        pass_data['username'] = request.user.username
        pass_data['amount'] = 20
        for i in request.POST:
            if i not in ['csrfmiddlewaretoken', 'login_submit']:
                pass_data[i] = request.POST[i]
        print(pass_data)
        db.insert_one(pass_data)
        return render(request, 'ticketbooking/book_action.html', {
            'value': '20Rs'
        })
    return render(request, 'ticketbooking/book.html')


@login_required
def tran(request):
    pass_value = list()
    for i in db.find({'username': request.user.username}).sort( [['_id', -1]] ):
        pass_value.append(i)
    return render(request, 'ticketbooking/transac.html', {'datas': pass_value})


@login_required
def receipt(request):
    return render(request, 'ticketbooking/Receipt.html', {
        'data': db.find_one({'username': request.user.username}, sort=[('_id', DESCENDING)])
    })

mysite/ticketbooking/templates/ticketbooking/Receipt.html
<h1><center>Your Ticket has been sucessfully booked<center></h1><br>
<center><h1>Ticket</h1></center>
	<center>Name : {{ data.username }}</center>
	<center>Source: {{ data.source }}</center>
	<center>Destination: {{ data.dest }}</center>
	<center>Class: {{ data.class }}</center>
	<center>No of Passengers : {{ data.number }}</center>
	<center>Type of ticket : {% if data.type == '1' %}Single{% else %}Return{% endif %}</center>
	<center>Amt Paid: {{ data.amount }}</center>
<html>
<head>
<link rel='stylesheet' href="{% static 'ticketbooking/index.css' %}">
<link rel="shortcut icon" href="logofig.jpg" />
<script>
function myFunction() {
    window.print();
}
</script>
</head>
<body style="background-color: F5F1F0;">

<table align = "Center">
<tr>
<td>
<button onclick="myFunction()">Print this page</button>
</td></tr>
<tr>
<td><a href="{% url 'ticket:index' %}"><button>Home</button></a>
</td>
</tr>
</body style="background-color: F5F1F0;">
</html>

mysite/ticketbooking/templates/ticketbooking/Transac.html
<html>
<head>
<link rel='stylesheet' href='index.css'>
<link rel="shortcut icon" href="logofig.jpg" />
<script>
function myFunction() {
    window.print();
}
</script>
</head>
<body style="background-color: F5F1F0;">
<div style="display:flex;flex-wrap:wrap;">
{% for data in datas %}
<div style="border:1px solid black; flex:40%; padding-bottom:10px;">
	<center><h1>Ticket</h1></center>
	<center>Name : {{ data.username }}</center>
	<center>Source: {{ data.source }}</center>
	<center>Destination: {{ data.dest }}</center>
	<center>Class: {{ data.class }}</center>
	<center>No of Passengers : {{ data.number }}</center>
	<center>Type of ticket : {% if data.type == '1' %}Single{% else %}Return{% endif %}</center>
	<center>Amt Paid: {{ data.amount }}</center>
</div>
{% endfor %}
	</div>
<table align = "Center">
<tr>
<td><a href="{% url 'ticket:index' %}"><button>Home</button></a>
</td>
</tr>
</body style="background-color: F5F1F0;">
</html>

mysite/ticketbooking/templates/ticketbooking/book.html
<html>
<head>
    {% load static %}
 <link rel='stylesheet' href="{% static 'ticketbooking/index.css' %}">
 <link rel="shortcut icon" href="logofig.jpg" />
<title>book</title>
</head>
<body style="background-color: F5F1F0;">
<center><img src="{% static 'ticketbooking/Logo.jpg' %}" width='35%'></center>
<form method='post' action ="{% url 'ticket:book' %}" >
    {% csrf_token %}
<table align="center">
<tr><td>Source: </td> 
<td colspan="2"><input list="Stations" name="source">
  <datalist id="Stations">
    <option value="Thane">
    <option value="Airoli">
    <option value="Rabale">
    <option value="Ghansoli">
    <option value="Kopar Khairane">
	<option value="Turbhe">
	<option value="Jui Nagar">
	<option value="Nerul">
  </datalist> </td>
  </tr>
<tr><td>Destination : </td> <td colspan="2"><input list="Stations" name="dest"></td></td></tr>
<tr><td>Class :</td><td><input type="radio" name="class" value='1'>I</td><td><input type="radio" name="class" value='2'>II</td></tr>
<tr><td>Type :</td><td><input type="radio" name="type" value='1'>One-Sided</td><td><input type="radio" name="type" value='2'>Return</td></tr>
<tr><td>Number of Tickets</td><td colspan="2"><input type="integer" name="number" ></td></tr>
<tr><td colspan='3'><center><button type='Submit' name='login_submit' >Book</button></center></td></tr>

<tr></tr>

</table>
    <center style="color:red">{{ msg }}</center>
</form>

mysite/ticketbooking/templates/ticketbooking/book_action.html
<html>
<head>
<link rel='stylesheet' href='index.css'>
<link rel="shortcut icon" href="logofig.jpg" />
<title> Registration Page </title>
</head>
<body style="background-color: F5F1F0;">
<center><img src="logohead.png" width='35%'></center>
<form method='post' action ="{% url 'ticket:receipt' %}" >
 {% csrf_token %}
<table align="center">
<tr><th colspan='3'>Enter your Card details:</th></tr>
<tr><td>Amount : </td> <td colspan='2'><input type="text" name="readonly" value="{{ value }}" readonly></td></tr>
<tr><td>Card Number : </td> <td colspan='2'><input type="Number" name="cno" maxlength='50'></td></tr>
<tr><td>Name on Card: </td> <td colspan='2'><input type="Text" name="name" maxlength='50'></td></tr>
<tr><td>Expiry Date : </td> <td><input type="Number" name="Em" placeholder='MM' maxlength='2'></td>
<td><input type="Number" name="Ey" placeholder='YY' maxlength='2'></td></tr>
<tr><td>CVV No: </td> <td colspan='2'><input type="Password" name="Cvv" maxlength='3'></td></tr>
<tr><td>PIN: </td> <td colspan='2'><input type="Password" name="Pin" maxlength='4'></td></tr>
<tr><td colspan='3'><center><button type='Submit' name='register_submit' >Make Payment</Button></center></td></tr>
</table>
</form>
</body style="background-color: F5F1F0;">
</html>

mysite/ticketbooking/templates/ticketbooking/home.html
<html><head>
 {% load static %}
<link rel='stylesheet' href="{% static 'ticketbooking/index.css' %}">

<link rel="shortcut icon" href="logofig.jpg" />
</head><body style="background-color: F5F1F0;">
<table align="right"><td></td></tr></table>

 <center><img style="width: 485px; height: 167px;" alt="EasyTrip" src="{% static 'ticketbooking/Logo.lpg' %}" ></center>
<hr>
<center><h1>Welcome {{ user.get_username }} </h1></center>
<center><h2>What do you want to do ?</h2></center>

<div><table id="home" style="width: 40%; height: 136px; text-align: left; margin-left: auto; margin-right: auto;" cellpadding="2" cellspacing="2"><tbody style="background-color: F5F1F0;">
<tr align="center"><td><a href="{% url 'ticket:book' %}"><button>Book Tickets</button></a></td>
</a></td></tr>
<tr align="center"><td><a href="{% url 'ticket:tran' %}"><button>Transactions</button></a></td>
</tr>
<tr align="center"> <td><a href="{% url 'ticket:logout' %}"><button>Logout</button></a></td></tbody style="background-color: F5F1F0;"></table>
</div>
</body style="background-color: F5F1F0;"></html>

mysite/ticketbooking/templates/ticketbooking/login.html
<html xmlns:ticke="http://www.w3.org/1999/xhtml">
<head>
 {% load static %}
 <link rel='stylesheet' href="{% static 'ticketbooking/index.css' %}">
 <link rel="shortcut icon" href="logofig.jpg" />
<title>Easytrip</title>
    {% load crispy_forms_tags %}
</head>
<body style="background-color: F5F1F0;">
<center><img src="{% static 'ticketbooking/Logo.jpg' %}" width='35%'></center>
<center>
<form method='post' action ="{% url 'ticket:login' %}" >
{% if user.is_authenticated %}
        <p>You are already logged in</p>
    {% else %}
        <form id ="login_form" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input onclick="load()" type="submit" value="login">
            <a href="{% url 'ticket:signup' %}"><input type="button" value="Signup"></a>
        </form>
    {% endif %}
</form>
    </center>
</body>
</html>

mysite/ticketbooking/templates/ticketbooking/register.html
<html>
<head>
{% load static%}
    <link rel='stylesheet' href="{% static 'ticketbooking/index.css' %}">
<link rel="shortcut icon" href=
        "logofig.jpg" />
<title> Registration Page </title>
</head>
<body style="background-color: F5F1F0;">
<center><img src="{% static 'ticketbooking/Logo.jpg' %}" width='35%'></center>
<form method='post' action ="{% url 'ticket:signup' %}" >
    {% csrf_token %}
    {{form}}
        <button type='Submit' name='register_submit' >Submit</Button>

</form>
</body style="background-color: F5F1F0;">
</html>